In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
from scipy.stats import linregress
import numpy as np

In [2]:
#File to load
file_to_load = "Car_sales_Data/car_data.csv"

# Read Purchasing File and store into Pandas data frame
car_data_df = pd.read_csv(file_to_load)
car_data_df.head()

,Brand,Autogroup,Avg Price,Q1 2019,Q2 2019,Q3 2019,Q4 2019,Q1 2020,Q2 2020,Q3 2020,Q4 2020
0,Acura,Honda,40000,36385.0,37382.0,39046.0,44572.0,28531.0,27458.0,39664.0,25681.0
1,Alfa Romeo,Fiat Chrysler,50000,4286.0,4751.0,4310.0,4947.0,3702.0,3735.0,5056.0,0.0
2,Audi,Audi,59017,48115.0,53325.0,57031.0,65640.0,41371.0,34839.0,47896.0,0.0
3,Bentley,VW,211000,2385.0,2385.0,2385.0,0.0,2499.0,2499.0,2499.0,0.0
4,BMW,BMW,69000,73888.0,82551.0,75987.0,92399.0,62152.0,50956.0,68439.0,0.0

In [3]:
#Remove column Q4 2019 & Q4 2020 as Quarter 4 data was not fully published at the time of the project.
drop_col=['Q4 2019', 'Q4 2020']
car_data_df = car_data_df.drop(drop_col, axis=1)

#Display results of dataframe
car_data_df

,Brand,Autogroup,Avg Price,Q1 2019,Q2 2019,Q3 2019,Q1 2020,Q2 2020,Q3 2020
0,Acura,Honda,40000,36385.0,37382.0,39046.0,28531.0,27458.0,39664.0
1,Alfa Romeo,Fiat Chrysler,50000,4286.0,4751.0,4310.0,3702.0,3735.0,5056.0
2,Audi,Audi,59017,48115.0,53325.0,57031.0,41371.0,34839.0,47896.0
3,Bentley,VW,211000,2385.0,2385.0,2385.0,2499.0,2499.0,2499.0
4,BMW,BMW,69000,73888.0,82551.0,75987.0,62152.0,50956.0,68439.0
5,Bugatti,VW,2400000,21.0,21.0,21.0,19.0,19.0,19.0
6,Buick,GM,33000,51865.0,55373.0,50614.0,33870.0,35521.0,49170.0
7,Cadillac,GM,54000,35996.0,39739.0,39962.0,30323.0,23297.0,32966.0
8,Chevrolet,GM,33000,451742.0,486884.0,505913.0,429529.0,330381.0,449134.0
9,Chrysler,Fiat Chrysler,32000,31591.0,32831.0,29544.0,29945.0,13857.0,31869.0
10,Dodge,Fiat Chrysler,29000,110517.0,117582.0,104146.0,88656.0,43756.0,71935.0
11,Ferrari,Ferrari,300000,2585.0,2585.0,2585.0,2147.0,2147.0,2147.0
12,Fiat,Fiat Chrysler,26000,2214.0,2889.0,2361.0,1128.0,1339.0,1102.0
13,Ford,Ford,32000,557884.0,613098.0,548070.0,489051.0,411035.0,521530.0
14,Genesis,Hyundai,49000,4203.0,5805.0,4902.0,3955.0,3585.0,3745.0
15,GMC,GM,35000,125579.0,151701.0,140790.0,118718.0,101759.0,132746.0
16,Honda,Honda,28000,333402.0,370026.0,390168.0,270253.0,266044.0,338769.0
17,Hyundai,Hyundai,30000,147585.0,185743.0,173028.0,130875.0,139378.0,170828.0
18,Infiniti,Nissan,45000,34315.0,28743.0,24876.0,25556.0,16097.0,17368.0
19,Jaguar,TaTa,52000,10222.0,6060.0,6150.0,7266.0,4320.0,4700.0
20,Jeep,Fiat Chrysler,30000,212804.0,243477.0,245474.0,182667.0,176713.0,222211.0
21,Kia,Kia,30000,136596.0,168248.0,158754.0,137945.0,125302.0,165013.0
22,Lamborghini,Audi,300000,2172.0,2172.0,2172.0,1877.0,1877.0,1877.0
23,Land Rover,TaTa,59000,25028.0,21095.0,20516.0,21936.0,14500.0,15899.0
24,Lexus,Toyota,56000,66791.0,68944.0,73816.0,56345.0,50458.0,75285.0
25,Lincoln,Ford,52000,24874.0,25941.0,27937.0,25562.0,21280.0,27555.0
26,Maserati,Fiat Chrysler,80000,6433.0,6433.0,6433.0,3967.0,3967.0,3967.0
27,Mazda,Mazda,25000,70831.0,67722.0,69612.0,67670.0,61199.0,74411.0
28,McLaren,McLaren,250000,1102.0,1102.0,1102.0,299.0,299.0,299.0
29,Mercedes-Benz,Daimler,58000,78667.0,80463.0,89636.0,75265.0,69505.0,84628.0
30,Mini,BMW,28000,8905.0,8678.0,10243.0,5236.0,5288.0,8974.0
31,Mitsubishi,Mitsubishi,22000,42070.0,29030.0,24474.0,35563.0,12197.0,24857.0
32,Nissan,Nissan,30000,331536.0,322442.0,302478.0,232048.0,161317.0,221754.0
33,Porsche,Porsche,73000,15024.0,15233.0,14805.0,11984.0,12193.0,15548.0
34,Ram,Fiat Chrysler,34000,137013.0,196155.0,179200.0,140486.0,127682.0,175174.0
35,Subaru,Subaru,31000,156754.0,182771.0,185804.0,130591.0,136519.0,169446.0
36,Tesla,Tesla,60000,30600.0,53300.0,54700.0,52800.0,36800.0,139300.0
37,Toyota,Toyota,34000,476925.0,539448.0,553378.0,439402.0,347571.0,483164.0
38,Volkswagen,VW,30000,85872.0,98736.0,93547.0,75065.0,69933.0,84514.0
39,Volvo,Volvo,50000,22058.0,28062.0,27305.0,19485.0,23770.0,30349.0

In [4]:
#Autogroup and Avg Price was not needed for this portion of the analysis as the focus is solely on quarterly sales.
drop_col=['Autogroup', 'Avg Price']
car_data_df = car_data_df.drop(drop_col, axis=1)

#Display results
car_data_df

            Brand   Q1 2019   Q2 2019   Q3 2019   Q1 2020   Q2 2020   Q3 2020
0           Acura   36385.0   37382.0   39046.0   28531.0   27458.0   39664.0
1      Alfa Romeo    4286.0    4751.0    4310.0    3702.0    3735.0    5056.0
2            Audi   48115.0   53325.0   57031.0   41371.0   34839.0   47896.0
3         Bentley    2385.0    2385.0    2385.0    2499.0    2499.0    2499.0
4             BMW   73888.0   82551.0   75987.0   62152.0   50956.0   68439.0
5         Bugatti      21.0      21.0      21.0      19.0      19.0      19.0
6           Buick   51865.0   55373.0   50614.0   33870.0   35521.0   49170.0
7        Cadillac   35996.0   39739.0   39962.0   30323.0   23297.0   32966.0
8       Chevrolet  451742.0  486884.0  505913.0  429529.0  330381.0  449134.0
9        Chrysler   31591.0   32831.0   29544.0   29945.0   13857.0   31869.0
10          Dodge  110517.0  117582.0  104146.0   88656.0   43756.0   71935.0
11        Ferrari    2585.0    2585.0    2585.0    2147.0    2147.0    2147.0
12           Fiat    2214.0    2889.0    2361.0    1128.0    1339.0    1102.0
13           Ford  557884.0  613098.0  548070.0  489051.0  411035.0  521530.0
14        Genesis    4203.0    5805.0    4902.0    3955.0    3585.0    3745.0
15            GMC  125579.0  151701.0  140790.0  118718.0  101759.0  132746.0
16          Honda  333402.0  370026.0  390168.0  270253.0  266044.0  338769.0
17        Hyundai  147585.0  185743.0  173028.0  130875.0  139378.0  170828.0
18       Infiniti   34315.0   28743.0   24876.0   25556.0   16097.0   17368.0
19         Jaguar   10222.0    6060.0    6150.0    7266.0    4320.0    4700.0
20           Jeep  212804.0  243477.0  245474.0  182667.0  176713.0  222211.0
21            Kia  136596.0  168248.0  158754.0  137945.0  125302.0  165013.0
22    Lamborghini    2172.0    2172.0    2172.0    1877.0    1877.0    1877.0
23     Land Rover   25028.0   21095.0   20516.0   21936.0   14500.0   15899.0
24          Lexus   66791.0   68944.0   73816.0   56345.0   50458.0   75285.0
25        Lincoln   24874.0   25941.0   27937.0   25562.0   21280.0   27555.0
26       Maserati    6433.0    6433.0    6433.0    3967.0    3967.0    3967.0
27          Mazda   70831.0   67722.0   69612.0   67670.0   61199.0   74411.0
28        McLaren    1102.0    1102.0    1102.0     299.0     299.0     299.0
29  Mercedes-Benz   78667.0   80463.0   89636.0   75265.0   69505.0   84628.0
30           Mini    8905.0    8678.0   10243.0    5236.0    5288.0    8974.0
31     Mitsubishi   42070.0   29030.0   24474.0   35563.0   12197.0   24857.0
32         Nissan  331536.0  322442.0  302478.0  232048.0  161317.0  221754.0
33        Porsche   15024.0   15233.0   14805.0   11984.0   12193.0   15548.0
34            Ram  137013.0  196155.0  179200.0  140486.0  127682.0  175174.0
35         Subaru  156754.0  182771.0  185804.0  130591.0  136519.0  169446.0
36          Tesla   30600.0   53300.0   54700.0   52800.0   36800.0  139300.0
37         Toyota  476925.0  539448.0  553378.0  439402.0  347571.0  483164.0
38     Volkswagen   85872.0   98736.0   93547.0   75065.0   69933.0   84514.0
39          Volvo   22058.0   28062.0   27305.0   19485.0   23770.0   30349.0

In [5]:
#Total sales for each brand for 2019
car_data_df["2019 Total Sales"] = car_data_df["Q1 2019"] + car_data_df["Q2 2019"] + car_data_df ["Q3 2019"]

#Display results
car_data_df

,Brand,Q1 2019,Q2 2019,Q3 2019,Q1 2020,Q2 2020,Q3 2020,2019 Total Sales
0,Acura,36385.0,37382.0,39046.0,28531.0,27458.0,39664.0,112813.0
1,Alfa Romeo,4286.0,4751.0,4310.0,3702.0,3735.0,5056.0,13347.0
2,Audi,48115.0,53325.0,57031.0,41371.0,34839.0,47896.0,158471.0
3,Bentley,2385.0,2385.0,2385.0,2499.0,2499.0,2499.0,7155.0
4,BMW,73888.0,82551.0,75987.0,62152.0,50956.0,68439.0,232426.0
5,Bugatti,21.0,21.0,21.0,19.0,19.0,19.0,63.0
6,Buick,51865.0,55373.0,50614.0,33870.0,35521.0,49170.0,157852.0
7,Cadillac,35996.0,39739.0,39962.0,30323.0,23297.0,32966.0,115697.0
8,Chevrolet,451742.0,486884.0,505913.0,429529.0,330381.0,449134.0,1444539.0
9,Chrysler,31591.0,32831.0,29544.0,29945.0,13857.0,31869.0,93966.0
10,Dodge,110517.0,117582.0,104146.0,88656.0,43756.0,71935.0,332245.0
11,Ferrari,2585.0,2585.0,2585.0,2147.0,2147.0,2147.0,7755.0
12,Fiat,2214.0,2889.0,2361.0,1128.0,1339.0,1102.0,7464.0
13,Ford,557884.0,613098.0,548070.0,489051.0,411035.0,521530.0,1719052.0
14,Genesis,4203.0,5805.0,4902.0,3955.0,3585.0,3745.0,14910.0
15,GMC,125579.0,151701.0,140790.0,118718.0,101759.0,132746.0,418070.0
16,Honda,333402.0,370026.0,390168.0,270253.0,266044.0,338769.0,1093596.0
17,Hyundai,147585.0,185743.0,173028.0,130875.0,139378.0,170828.0,506356.0
18,Infiniti,34315.0,28743.0,24876.0,25556.0,16097.0,17368.0,87934.0
19,Jaguar,10222.0,6060.0,6150.0,7266.0,4320.0,4700.0,22432.0
20,Jeep,212804.0,243477.0,245474.0,182667.0,176713.0,222211.0,701755.0
21,Kia,136596.0,168248.0,158754.0,137945.0,125302.0,165013.0,463598.0
22,Lamborghini,2172.0,2172.0,2172.0,1877.0,1877.0,1877.0,6516.0
23,Land Rover,25028.0,21095.0,20516.0,21936.0,14500.0,15899.0,66639.0
24,Lexus,66791.0,68944.0,73816.0,56345.0,50458.0,75285.0,209551.0
25,Lincoln,24874.0,25941.0,27937.0,25562.0,21280.0,27555.0,78752.0
26,Maserati,6433.0,6433.0,6433.0,3967.0,3967.0,3967.0,19299.0
27,Mazda,70831.0,67722.0,69612.0,67670.0,61199.0,74411.0,208165.0
28,McLaren,1102.0,1102.0,1102.0,299.0,299.0,299.0,3306.0
29,Mercedes-Benz,78667.0,80463.0,89636.0,75265.0,69505.0,84628.0,248766.0
30,Mini,8905.0,8678.0,10243.0,5236.0,5288.0,8974.0,27826.0
31,Mitsubishi,42070.0,29030.0,24474.0,35563.0,12197.0,24857.0,95574.0
32,Nissan,331536.0,322442.0,302478.0,232048.0,161317.0,221754.0,956456.0
33,Porsche,15024.0,15233.0,14805.0,11984.0,12193.0,15548.0,45062.0
34,Ram,137013.0,196155.0,179200.0,140486.0,127682.0,175174.0,512368.0
35,Subaru,156754.0,182771.0,185804.0,130591.0,136519.0,169446.0,525329.0
36,Tesla,30600.0,53300.0,54700.0,52800.0,36800.0,139300.0,138600.0
37,Toyota,476925.0,539448.0,553378.0,439402.0,347571.0,483164.0,1569751.0
38,Volkswagen,85872.0,98736.0,93547.0,75065.0,69933.0,84514.0,278155.0
39,Volvo,22058.0,28062.0,27305.0,19485.0,23770.0,30349.0,77425.0

In [6]:
#Total sales for each brand for 2020
car_data_df["2020 Total Sales"] = car_data_df["Q1 2020"] + car_data_df["Q2 2020"] + car_data_df ["Q3 2020"]

#Display results 
car_data_df

,Brand,Q1 2019,Q2 2019,Q3 2019,Q1 2020,Q2 2020,Q3 2020,2019 Total Sales,2020 Total Sales
0,Acura,36385.0,37382.0,39046.0,28531.0,27458.0,39664.0,112813.0,95653.0
1,Alfa Romeo,4286.0,4751.0,4310.0,3702.0,3735.0,5056.0,13347.0,12493.0
2,Audi,48115.0,53325.0,57031.0,41371.0,34839.0,47896.0,158471.0,124106.0
3,Bentley,2385.0,2385.0,2385.0,2499.0,2499.0,2499.0,7155.0,7497.0
4,BMW,73888.0,82551.0,75987.0,62152.0,50956.0,68439.0,232426.0,181547.0
5,Bugatti,21.0,21.0,21.0,19.0,19.0,19.0,63.0,57.0
6,Buick,51865.0,55373.0,50614.0,33870.0,35521.0,49170.0,157852.0,118561.0
7,Cadillac,35996.0,39739.0,39962.0,30323.0,23297.0,32966.0,115697.0,86586.0
8,Chevrolet,451742.0,486884.0,505913.0,429529.0,330381.0,449134.0,1444539.0,1209044.0
9,Chrysler,31591.0,32831.0,29544.0,29945.0,13857.0,31869.0,93966.0,75671.0
10,Dodge,110517.0,117582.0,104146.0,88656.0,43756.0,71935.0,332245.0,204347.0
11,Ferrari,2585.0,2585.0,2585.0,2147.0,2147.0,2147.0,7755.0,6441.0
12,Fiat,2214.0,2889.0,2361.0,1128.0,1339.0,1102.0,7464.0,3569.0
13,Ford,557884.0,613098.0,548070.0,489051.0,411035.0,521530.0,1719052.0,1421616.0
14,Genesis,4203.0,5805.0,4902.0,3955.0,3585.0,3745.0,14910.0,11285.0
15,GMC,125579.0,151701.0,140790.0,118718.0,101759.0,132746.0,418070.0,353223.0
16,Honda,333402.0,370026.0,390168.0,270253.0,266044.0,338769.0,1093596.0,875066.0
17,Hyundai,147585.0,185743.0,173028.0,130875.0,139378.0,170828.0,506356.0,441081.0
18,Infiniti,34315.0,28743.0,24876.0,25556.0,16097.0,17368.0,87934.0,59021.0
19,Jaguar,10222.0,6060.0,6150.0,7266.0,4320.0,4700.0,22432.0,16286.0
20,Jeep,212804.0,243477.0,245474.0,182667.0,176713.0,222211.0,701755.0,581591.0
21,Kia,136596.0,168248.0,158754.0,137945.0,125302.0,165013.0,463598.0,428260.0
22,Lamborghini,2172.0,2172.0,2172.0,1877.0,1877.0,1877.0,6516.0,5631.0
23,Land Rover,25028.0,21095.0,20516.0,21936.0,14500.0,15899.0,66639.0,52335.0
24,Lexus,66791.0,68944.0,73816.0,56345.0,50458.0,75285.0,209551.0,182088.0
25,Lincoln,24874.0,25941.0,27937.0,25562.0,21280.0,27555.0,78752.0,74397.0
26,Maserati,6433.0,6433.0,6433.0,3967.0,3967.0,3967.0,19299.0,11901.0
27,Mazda,70831.0,67722.0,69612.0,67670.0,61199.0,74411.0,208165.0,203280.0
28,McLaren,1102.0,1102.0,1102.0,299.0,299.0,299.0,3306.0,897.0
29,Mercedes-Benz,78667.0,80463.0,89636.0,75265.0,69505.0,84628.0,248766.0,229398.0
30,Mini,8905.0,8678.0,10243.0,5236.0,5288.0,8974.0,27826.0,19498.0
31,Mitsubishi,42070.0,29030.0,24474.0,35563.0,12197.0,24857.0,95574.0,72617.0
32,Nissan,331536.0,322442.0,302478.0,232048.0,161317.0,221754.0,956456.0,615119.0
33,Porsche,15024.0,15233.0,14805.0,11984.0,12193.0,15548.0,45062.0,39725.0
34,Ram,137013.0,196155.0,179200.0,140486.0,127682.0,175174.0,512368.0,443342.0
35,Subaru,156754.0,182771.0,185804.0,130591.0,136519.0,169446.0,525329.0,436556.0
36,Tesla,30600.0,53300.0,54700.0,52800.0,36800.0,139300.0,138600.0,228900.0
37,Toyota,476925.0,539448.0,553378.0,439402.0,347571.0,483164.0,1569751.0,1270137.0
38,Volkswagen,85872.0,98736.0,93547.0,75065.0,69933.0,84514.0,278155.0,229512.0
39,Volvo,22058.0,28062.0,27305.0,19485.0,23770.0,30349.0,77425.0,73604.0

In [7]:
#Find the percentage change of sales between 2019 & 2020 sales
car_data_df["Percent Change"] = ((car_data_df["2020 Total Sales"] - car_data_df["2019 Total Sales"]) / car_data_df["2019 Total Sales"]) * 100

car_data_df['Percent Change'] = car_data_df['Percent Change'].map("{:,.0f}%".format)

#Display results
car_data_df

,Brand,Q1 2019,Q2 2019,Q3 2019,Q1 2020,Q2 2020,Q3 2020,2019 Total Sales,2020 Total Sales,Percent Change
0,Acura,36385.0,37382.0,39046.0,28531.0,27458.0,39664.0,112813.0,95653.0,-15%
1,Alfa Romeo,4286.0,4751.0,4310.0,3702.0,3735.0,5056.0,13347.0,12493.0,-6%
2,Audi,48115.0,53325.0,57031.0,41371.0,34839.0,47896.0,158471.0,124106.0,-22%
3,Bentley,2385.0,2385.0,2385.0,2499.0,2499.0,2499.0,7155.0,7497.0,5%
4,BMW,73888.0,82551.0,75987.0,62152.0,50956.0,68439.0,232426.0,181547.0,-22%
5,Bugatti,21.0,21.0,21.0,19.0,19.0,19.0,63.0,57.0,-10%
6,Buick,51865.0,55373.0,50614.0,33870.0,35521.0,49170.0,157852.0,118561.0,-25%
7,Cadillac,35996.0,39739.0,39962.0,30323.0,23297.0,32966.0,115697.0,86586.0,-25%
8,Chevrolet,451742.0,486884.0,505913.0,429529.0,330381.0,449134.0,1444539.0,1209044.0,-16%
9,Chrysler,31591.0,32831.0,29544.0,29945.0,13857.0,31869.0,93966.0,75671.0,-19%
10,Dodge,110517.0,117582.0,104146.0,88656.0,43756.0,71935.0,332245.0,204347.0,-38%
11,Ferrari,2585.0,2585.0,2585.0,2147.0,2147.0,2147.0,7755.0,6441.0,-17%
12,Fiat,2214.0,2889.0,2361.0,1128.0,1339.0,1102.0,7464.0,3569.0,-52%
13,Ford,557884.0,613098.0,548070.0,489051.0,411035.0,521530.0,1719052.0,1421616.0,-17%
14,Genesis,4203.0,5805.0,4902.0,3955.0,3585.0,3745.0,14910.0,11285.0,-24%
15,GMC,125579.0,151701.0,140790.0,118718.0,101759.0,132746.0,418070.0,353223.0,-16%
16,Honda,333402.0,370026.0,390168.0,270253.0,266044.0,338769.0,1093596.0,875066.0,-20%
17,Hyundai,147585.0,185743.0,173028.0,130875.0,139378.0,170828.0,506356.0,441081.0,-13%
18,Infiniti,34315.0,28743.0,24876.0,25556.0,16097.0,17368.0,87934.0,59021.0,-33%
19,Jaguar,10222.0,6060.0,6150.0,7266.0,4320.0,4700.0,22432.0,16286.0,-27%
20,Jeep,212804.0,243477.0,245474.0,182667.0,176713.0,222211.0,701755.0,581591.0,-17%
21,Kia,136596.0,168248.0,158754.0,137945.0,125302.0,165013.0,463598.0,428260.0,-8%
22,Lamborghini,2172.0,2172.0,2172.0,1877.0,1877.0,1877.0,6516.0,5631.0,-14%
23,Land Rover,25028.0,21095.0,20516.0,21936.0,14500.0,15899.0,66639.0,52335.0,-21%
24,Lexus,66791.0,68944.0,73816.0,56345.0,50458.0,75285.0,209551.0,182088.0,-13%
25,Lincoln,24874.0,25941.0,27937.0,25562.0,21280.0,27555.0,78752.0,74397.0,-6%
26,Maserati,6433.0,6433.0,6433.0,3967.0,3967.0,3967.0,19299.0,11901.0,-38%
27,Mazda,70831.0,67722.0,69612.0,67670.0,61199.0,74411.0,208165.0,203280.0,-2%
28,McLaren,1102.0,1102.0,1102.0,299.0,299.0,299.0,3306.0,897.0,-73%
29,Mercedes-Benz,78667.0,80463.0,89636.0,75265.0,69505.0,84628.0,248766.0,229398.0,-8%
30,Mini,8905.0,8678.0,10243.0,5236.0,5288.0,8974.0,27826.0,19498.0,-30%
31,Mitsubishi,42070.0,29030.0,24474.0,35563.0,12197.0,24857.0,95574.0,72617.0,-24%
32,Nissan,331536.0,322442.0,302478.0,232048.0,161317.0,221754.0,956456.0,615119.0,-36%
33,Porsche,15024.0,15233.0,14805.0,11984.0,12193.0,15548.0,45062.0,39725.0,-12%
34,Ram,137013.0,196155.0,179200.0,140486.0,127682.0,175174.0,512368.0,443342.0,-13%
35,Subaru,156754.0,182771.0,185804.0,130591.0,136519.0,169446.0,525329.0,436556.0,-17%
36,Tesla,30600.0,53300.0,54700.0,52800.0,36800.0,139300.0,138600.0,228900.0,65%
37,Toyota,476925.0,539448.0,553378.0,439402.0,347571.0,483164.0,1569751.0,1270137.0,-19%
38,Volkswagen,85872.0,98736.0,93547.0,75065.0,69933.0,84514.0,278155.0,229512.0,-17%
39,Volvo,22058.0,28062.0,27305.0,19485.0,23770.0,30349.0,77425.0,73604.0,-5%

In [8]:
#Sort Percent Change column by highest to lowest to get Top 5 high & low vehicles
car_data_df = car_data_df.sort_values(
["Brand", "Percent Change"], ascending=False)
car_data_df.head(10)

,Brand,Q1 2019,Q2 2019,Q3 2019,Q1 2020,Q2 2020,Q3 2020,2019 Total Sales,2020 Total Sales,Percent Change
39,Volvo,22058.0,28062.0,27305.0,19485.0,23770.0,30349.0,77425.0,73604.0,-5%
38,Volkswagen,85872.0,98736.0,93547.0,75065.0,69933.0,84514.0,278155.0,229512.0,-17%
37,Toyota,476925.0,539448.0,553378.0,439402.0,347571.0,483164.0,1569751.0,1270137.0,-19%
36,Tesla,30600.0,53300.0,54700.0,52800.0,36800.0,139300.0,138600.0,228900.0,65%
35,Subaru,156754.0,182771.0,185804.0,130591.0,136519.0,169446.0,525329.0,436556.0,-17%
34,Ram,137013.0,196155.0,179200.0,140486.0,127682.0,175174.0,512368.0,443342.0,-13%
33,Porsche,15024.0,15233.0,14805.0,11984.0,12193.0,15548.0,45062.0,39725.0,-12%
32,Nissan,331536.0,322442.0,302478.0,232048.0,161317.0,221754.0,956456.0,615119.0,-36%
31,Mitsubishi,42070.0,29030.0,24474.0,35563.0,12197.0,24857.0,95574.0,72617.0,-24%
30,Mini,8905.0,8678.0,10243.0,5236.0,5288.0,8974.0,27826.0,19498.0,-30%